name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: chartboost/ruff-action@v1
        with:
          python-version: '3.12'
          args: check .
          fix_args: --fix .
          config: .pyproject.toml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style fixes by ruff'
  tests:
    runs-on: ubuntu-latest
    if: always() && needs.lint.result == 'success'
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: |
          pip install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - name: set pythonpath
        run: |
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Test with pytest
        run: |
          cd tests
          poetry run pytest
