name: Lint and Commit
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: chartboost/ruff-action@v1
        with:
          python-version: "3.12"
          args: check .
          fix_args: --fix .
          config: .pyproject.toml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style fixes by ruff'